### PR TITLE
Replaced request and lodash

### PR DESCRIPTION
**Pull request by StephanGeorg**
I replaced request with [isomorphic-fetch](https://github.com/matthew-andrews/isomorphic-fetch) so that you can use this in isomorphic environments. I also replaced lodash map/bind with the native functions. In the next step I would completely rewrite it in es6 and implement it with babel. What you think?

### CODE REVIEW

**Comment by StephanGeorg** [comment]
Ah, I saw the checks failed due to missing apiKey. Can you add one to the Travis tests?

**Comment by tsamaya** [comment]
Hi Stephan,

yes travis can not run on PR.
I will have a look later this week.
anycase it sounds promising and interesting thanks for your work.

Arnaud

**Comment by tsamaya** [comment]
Hi Stephan
seems OK for me, can you please bump version before I merge with:
`$ grunt version::minor`

**Comment by tsamaya** [comment]
Can you also bump the version in https://github.com/StephanGeorg/w3w-node-wrapper/blob/master/lib/W3W.Geocoder.js#L21

that was the purpose of the command line with grunt 😉

**Comment by StephanGeorg** [comment]
Can you please publish it to NPM.

**Comment by tsamaya** [comment]
I removed the IOJS platform from list for the CI . Tests now pass
and it is then published on NPM
Great Stuff, thank you.

**Pull request merged**
